<!--
 SPDX-FileCopyrightText: Copyright (c) 2009-2026 TRUMPF Laser GmbH, authors: C-Labs
 SPDX-License-Identifier: MPL-2.0
 -->
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0</TargetFrameworks>
		<RootNamespace>nsCDEngine</RootNamespace>
		<AssemblyName>C-DEngine</AssemblyName>
		<PackageId>C-DEngine</PackageId>
		<PackageIcon>toplogo-128.png</PackageIcon>
		<PackageReadmeFile>readme.md</PackageReadmeFile>		
		<Version>7.107.0</Version>
		<Authors>Chris Muench</Authors>
		<Company>C-Labs</Company>
		<Product>C-DEngine for $(TargetFramework)$(cdeDebugProductSuffix)</Product>
		<NeutralLanguage>en</NeutralLanguage>
		<Description>C-Labs Distributed Engine</Description>
		<PackageDescription>C-Labs Distributed Engine</PackageDescription>
		<Copyright>Copyright © 2017-2026 TRUMPF Laser GmbH, authors: C-Labs, Hyviva</Copyright>
		<PackageLicenseExpression>MPL-2.0</PackageLicenseExpression>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<!-- Workaround for placing each DLL into a separate directory when using msbuild's GenerateProjectSpecificOutputFolder -->
		<ProjectName>$(AssemblyName).$(TargetFramework)</ProjectName>
		<!-- Workaround for placing the .nupkg into the build's output folder when using msbuild's GenerateProjectSpecificOutputFolder -->
		<PackageOutputPath>$(SolutionDir)Nugets</PackageOutputPath>
		<DefineConstants>TRACE;CDE_SYSLOG;CDE_JSONET</DefineConstants>
		<LangVersion>preview</LangVersion>
		<DocumentationFile>$(OutputPath)C-DEngine.xml</DocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="toplogo-128.png" Pack="true" PackagePath="" />
		<None Include="..\..\readme.md" Pack="true" PackagePath="\" />
		<EmbeddedResource Include="C-DCommunication\ClientBin\FAVICON.ICO" />
	</ItemGroup>

	<!-- MarkusH 2020/02/10: nuget restore does not set a proper solution path: fix it up -->
	<PropertyGroup Condition=" ('$(SolutionPath)' == '' OR !Exists('$(SolutionPath)'))AND  '$(SolutionDir)' != '' AND '$(SolutionDir)' != '*undefined*' and Exists('$(SolutionDir)$(SolutionName).SLN')">
		<SolutionPath>$(SolutionDir)$(SolutionName).SLN</SolutionPath>
	</PropertyGroup>
	<PropertyGroup Condition=" ('$(SolutionPath)' == '' OR !Exists('$(SolutionPath)'))AND  '$(SolutionDir)' != '' AND '$(SolutionDir)' != '*undefined*' and Exists('$(SolutionDir)$(SolutionName).SLNX')">
		<SolutionPath>$(SolutionDir)$(SolutionName).SLNX</SolutionPath>
	</PropertyGroup>

	<PropertyGroup>
	  <NoWarn>1701;1702;CS1591</NoWarn>
	  <NoWarn>1701;1702;CS1591</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<None Update="C-DEngine.CDES">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<Target Name="GetPackagingOutputs" />

	<ItemGroup>
		<PackageReference Include="System.Drawing.Common" Version="10.0.10" />
	</ItemGroup>

	<Target Name="CopyUpdaterEXEBeforeBuild" BeforeTargets="BeforeBuild">
		<MSBuild Projects="@(ProjectReference)" Targets="GetTargetPath" BuildInParallel="false" Condition="'%(Name)'=='cdeUpdater'">
			<Output TaskParameter="TargetOutputs" ItemName="DependentAssemblies" />
		</MSBuild>
		<Copy SourceFiles="@(DependentAssemblies)" DestinationFolder="$(OutputPath)" SkipUnchangedFiles="true" Retries="10" RetryDelayMilliseconds="5000" />
	</Target>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="call &quot;$(ProjectDir)..\..\BuildTools\signMeSha.bat&quot; &quot;$(TargetDir)$(TargetFileName)&quot;" />
	</Target>
</Project>

