name: .NET Core

# SPDX-FileCopyrightText: Copyright (c) 2009-2020 TRUMPF Laser GmbH, authors: C-Labs
# SPDX-License-Identifier: CC0-1.0

on:
  push:
    branches: [ main, master ]
    tags: [ '[1-9]+.[0-9]+.[0-9]+*' ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:

    runs-on: windows-2019

    env: 
        cdePackagerCheckOverwrite : true

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          3.1.201
          7.0
          6.0
          5.0
        source-url: https://api.nuget.org/v3/index.json
        config-file: .\nuget.config
        owner: ${{secrets.NUGETORG_APIKEY_OWNER}}
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGETORG_APIKEY}}

    # gitversion requires full history and tags
    - name: Fetch unshallow
      run: git fetch --prune --tags --unshallow

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.9
      with:
          versionSpec: '5.6.6'

    - name: Use GitVersion
      id: gitversion # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v0.9.9
      env:
        DOTNET_ROLL_FORWARD: Major

    - name: Gitversion info
      run: |
        echo "Major: ${{ steps.gitversion.outputs.major }}"
        echo "Minor: ${{ steps.gitversion.outputs.minor }}"
        echo "Patch: ${{ steps.gitversion.outputs.patch }}"
        echo "PreReleaseTag: ${{ steps.gitversion.outputs.preReleaseTag }}"
        echo "PreReleaseTagWithDash: ${{ steps.gitversion.outputs.preReleaseTagWithDash }}"
        echo "PreReleaseLabel: ${{ steps.gitversion.outputs.preReleaseLabel }}"
        echo "PreReleaseNumber: ${{ steps.gitversion.outputs.preReleaseNumber }}"
        echo "WeightedPreReleaseNumber: ${{ steps.gitversion.outputs.weightedPreReleaseNumber }}"
        echo "BuildMetaData: ${{ steps.gitversion.outputs.buildMetaData }}"
        echo "BuildMetaDataPadded: ${{ steps.gitversion.outputs.buildMetaDataPadded }}"
        echo "FullBuildMetaData: ${{ steps.gitversion.outputs.fullBuildMetaData }}"
        echo "MajorMinorPatch: ${{ steps.gitversion.outputs.majorMinorPatch }}"
        echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"
        echo "LegacySemVer: ${{ steps.gitversion.outputs.legacySemVer }}"
        echo "LegacySemVerPadded: ${{ steps.gitversion.outputs.legacySemVerPadded }}"
        echo "AssemblySemVer: ${{ steps.gitversion.outputs.assemblySemVer }}"
        echo "AssemblySemFileVer: ${{ steps.gitversion.outputs.assemblySemFileVer }}"
        echo "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"
        echo "InformationalVersion: ${{ steps.gitversion.outputs.informationalVersion }}"
        echo "BranchName: ${{ steps.gitversion.outputs.branchName }}"
        echo "Sha: ${{ steps.gitversion.outputs.sha }}"
        echo "ShortSha: ${{ steps.gitversion.outputs.shortSha }}"
        echo "NuGetVersionV2: ${{ steps.gitversion.outputs.nuGetVersionV2 }}"
        echo "NuGetVersion: ${{ steps.gitversion.outputs.nuGetVersion }}"
        echo "NuGetPreReleaseTagV2: ${{ steps.gitversion.outputs.nuGetPreReleaseTagV2 }}"
        echo "NuGetPreReleaseTag: ${{ steps.gitversion.outputs.nuGetPreReleaseTag }}"
        echo "VersionSourceSha: ${{ steps.gitversion.outputs.versionSourceSha }}"
        echo "CommitsSinceVersionSource: ${{ steps.gitversion.outputs.commitsSinceVersionSource }}"
        echo "CommitsSinceVersionSourcePadded: ${{ steps.gitversion.outputs.commitsSinceVersionSourcePadded }}"
        echo "CommitDate: ${{ steps.gitversion.outputs.commitDate }}"

    - name: Install code sign cert
      run: |
        try {
          Import-Module PKI
          Set-Content -value ([Convert]::FromBase64String("${{secrets.CodeSignCert}}")) -path ".\signcert.pfx" -encoding Byte
          import-pfxcertificate -filepath ".\signcert.pfx" -CertStoreLocation "Cert:\CurrentUser\My" -password (ConvertTo-SecureString -String "${{secrets.CodeSignCertPassword}}" -AsPlainText -Force)
          remove-item ".\signcert.pfx"
          Set-Content -path ".\BuildTools\\real.sign" -value ""
        } catch { write-host $_; throw $_ }
      shell: powershell

    - name: Install dependencies
      run: dotnet restore './src/C-DEngine.sln'

    # Workaround for gitversiontask lock exception: build a single targetframework first
    - name: Build cdeUpdater Net48
      run: dotnet build './src/Utilities/cdeUpdater/cdeUpdater.csproj' --framework net48 --configuration Release --no-restore --disable-parallel /nowarn:nu5105

    - name: Build cdeUpdater
      run: dotnet build './src/Utilities/cdeUpdater/cdeUpdater.csproj' --configuration Release --no-restore --disable-parallel /nowarn:nu5105

    - name: Build
      run: dotnet build './src/C-DEngine.sln' --configuration Release --no-restore --disable-parallel /nowarn:CS1591 /nowarn:nu5105

    - name: Create C-DEngine.CDEX
      run: .\src\C-DEngine\packagecde.cmd Release
      shell: cmd

    - name: Test
      run: dotnet test './src/C-DEngine.sln' --configuration Release --no-build --no-restore --verbosity normal

    - name: Gather artifacts
      run: (robocopy .\bin\ .\artifacts\ *.CDEX *.CDEP *.nupkg *.snupkg *.msi cdePackager* /s /np) ^& IF %ERRORLEVEL% LEQ 1 exit 0
      shell: cmd
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: C-DEngine
        path: ./artifacts

    - name: REUSE Compliance Check
      run: |
        pip3 install --user python-debian==0.1.38 # newer versions fail on Windows as of January 2021
        pip3 install --user reuse
        reuse lint

    - name: Push NuGet Packages
      # Only publish if the commit was tagged
      if: steps.gitversion.outputs.VersionSourceSha == steps.gitversion.outputs.Sha
      # this should work, but doesn't:
      #run: dotnet nuget push './artifacts/**/*.nupkg' -s Source -k ${{secrets.GITHUB_TOKEN}}
      # workaround:
      run: "Get-ChildItem ./artifacts/*.nupkg -File -Recurse | Foreach { $retryCount=0; do { if ($retryCount -gt 0) {start-sleep 30}; dotnet nuget push $_.fullname -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGETORG_APIKEY}}; $retryCount = $retryCount + 1 } while (($retryCount -lt 10) -and ($LastExitCode -ne 0)); if ($retryCount -ge 10) { throw(\"Error pushing to NuGet: \"+$LastExitCode) } }"
